version: '3'

services:
  db:
    platform: linux/amd64
    image: mysql
    container_name: tipsen-db
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tipsen
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - tipsen
  minio:
    container_name: tipsen-minio
    image: minio/minio
    ports:
      - 8081:9000
      - 8082:9001
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"
    networks:
      - tipsen
networks:
  tipsen:
    driver: bridge
